// time formatter for react time ago.
export const customFormatter = (
  value: number,
  unit: string,
  suffix: string
) => {
  if (unit === "second" && value < 60) {
    return "just now";
  }

  const shortUnit = {
    second: "s",
    minute: "m",
    hour: "h",
    day: "d",
    week: "w",
    month: "m",
    year: "y",
  }[unit];

  return `${value}${shortUnit} ago`;
};

export const expertise = [
  {
    label: "Programming Languages",
    items: [
      "JavaScript",
      "TypeScript",
      "Python",
      "Java",
      "C",
      "C++",
      "C#",
      "Go",
      "Rust",
      "Ruby",
      "PHP",
      "Swift",
      "Kotlin",
      "Dart",
      "R",
      "MATLAB",
      "Perl",
      "Scala",
      "Shell Scripting",
      "SQL",
      "NoSQL",
      "Assembly",
      "Haskell",
      "Lua",
      "Elixir",
      "Erlang",
      "Clojure",
      "F#",
      "VB.NET",
      "Groovy",
      "Fortran",
      "COBOL",
      "Prolog",
      "Ada",
      "Julia",
    ],
  },
  {
    label: "Frontend Development",
    items: [
      "HTML",
      "CSS",
      "SASS",
      "LESS",
      "Tailwind CSS",
      "Bootstrap",
      "React",
      "Next.js",
      "Vue.js",
      "Nuxt.js",
      "Angular",
      "Svelte",
      "SvelteKit",
      "Qwik",
      "Stencil",
      "Backbone.js",
    ],
  },
  {
    label: "Backend Development",
    items: [
      "Node.js",
      "Express.js",
      "Fastify",
      "NestJS",
      "Django",
      "Flask",
      "Spring Boot",
      "Ruby on Rails",
      "Laravel",
      "ASP.NET",
      "Koa",
      "Hapi.js",
      "Phoenix",
      "FastAPI",
    ],
  },
  {
    label: "DevOps & Cloud",
    items: [
      "Docker",
      "Kubernetes",
      "Terraform",
      "Ansible",
      "Chef",
      "Puppet",
      "Jenkins",
      "CircleCI",
      "GitHub Actions",
      "GitLab CI/CD",
      "AWS",
      "Azure",
      "Google Cloud",
      "Heroku",
      "Netlify",
      "Vercel",
      "Firebase",
      "Cloudflare",
    ],
  },
  {
    label: "Databases",
    items: [
      "MySQL",
      "PostgreSQL",
      "MongoDB",
      "SQLite",
      "Redis",
      "MariaDB",
      "OracleDB",
      "Cassandra",
      "Elasticsearch",
      "CouchDB",
      "DynamoDB",
      "GraphQL",
      "Prisma",
      "Supabase",
    ],
  },
  {
    label: "Mobile Development",
    items: [
      "React Native",
      "Flutter",
      "SwiftUI",
      "Jetpack Compose",
      "Xamarin",
      "Ionic",
    ],
  },
  {
    label: "Game Development",
    items: [
      "Unity",
      "Unreal Engine",
      "Godot",
      "Cocos2d",
      "CryEngine",
      "Pygame",
    ],
  },
  {
    label: "Specialized Domains",
    items: [
      "Frontend",
      "Backend",
      "Full Stack",
      "DevOps",
      "Data Science",
      "Machine Learning",
      "Artificial Intelligence",
      "Big Data",
      "Cybersecurity",
      "Blockchain",
      "Game Development",
      "Embedded Systems",
      "IoT (Internet of Things)",
      "Cloud Computing",
      "AR/VR",
      "Testing/QA",
      "Performance Engineering",
    ],
  },
  {
    label: "Version Control & Tools",
    items: ["Git", "GitHub", "GitLab", "Bitbucket", "SVN", "Mercurial"],
  },
  {
    label: "Miscellaneous",
    items: [
      "REST APIs",
      "GraphQL APIs",
      "WebSockets",
      "Microservices",
      "Serverless",
      "Monorepos",
      "TDD (Test-Driven Development)",
      "BDD (Behavior-Driven Development)",
      "Agile",
      "Scrum",
      "Kanban",
      "CI/CD",
    ],
  },
];
